# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='enter the first name of user', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text='enter the last name', max_length=100, null=True)),
                ('address', models.CharField(blank=True, help_text='enter the address', max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='enter the phone number', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='enter the email', max_length=100, null=True)),
                ('username', models.CharField(blank=True, help_text='enter the username', max_length=100, null=True)),
                ('password', models.CharField(blank=True, help_text='enter the password', max_length=100, null=True)),
            ],
        ),
    ]
