# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
