# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder_app', '0002_user_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
