# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder_app', '0005_auto_20170716_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, help_text='Enter the occupation name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='votes',
            field=models.IntegerField(default=0, help_text='Enter the age'),
        ),
    ]
