# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder_app', '0006_auto_20170716_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='votes',
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, help_text='Enter the college', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.CharField(blank=True, help_text='Enter the employer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, help_text='Enter the age', max_length=100, null=True),
        ),
    ]
